networks:
  my:
    external: true

services:
  flask-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: flask
    ports: 
      - "${FLASK_PORT}:9000"
    env_file:
     - ../.env
    depends_on:
     - postgres-db
    command: "sh /entrypoint.sh"
    volumes:
      - ..:/app/
      - static_files:/app/static
    networks:
      - my

volumes:
  static_files: