networks:
  my:
    external: true

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "${POSTGRES_PORT}:5439"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
     - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    command: ["postgres", "-c", "port=5439"]
    networks:
      - my

volumes:
  postgres_data: