"""empty message

Revision ID: 174c7b94351a
Revises: 3aeff8707604
Create Date: 2025-05-14 11:06:04.957165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174c7b94351a'
down_revision = '3aeff8707604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_type', sa.Enum('regular', 'important', 'new', name='newstype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('news_type')

    # ### end Alembic commands ###
