"""empty message

Revision ID: 317ecf3e5525
Revises: abeaefd2f97d
Create Date: 2025-05-15 14:37:11.053975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317ecf3e5525'
down_revision = 'abeaefd2f97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.drop_constraint('author', type_='foreignkey')
        batch_op.create_foreign_key(None, 'carts', ['cart_id'], ['id'])
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('author', 'users', ['user_id'], ['id'])
        batch_op.drop_column('quantity')
        batch_op.drop_column('product_id')
        batch_op.drop_column('cart_id')

    # ### end Alembic commands ###
