"""empty message

Revision ID: abeaefd2f97d
Revises: b0f16868f6e2
Create Date: 2025-05-15 14:31:45.375435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abeaefd2f97d'
down_revision = 'b0f16868f6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('picture1', sa.VARCHAR(length=200), nullable=True),
    sa.Column('picture2', sa.VARCHAR(length=200), nullable=True),
    sa.Column('picture3', sa.VARCHAR(length=200), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(length=300), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('catergory', sa.VARCHAR(length=12), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_visible', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('is_visible IN (0, 1)'),
    sa.CheckConstraint('is_visible IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
