"""empty message

Revision ID: b0f16868f6e2
Revises: 174c7b94351a
Create Date: 2025-05-15 09:51:04.582065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f16868f6e2'
down_revision = '174c7b94351a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(create_constraint=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
